### ISSUE TITLE
Implement $select filter

### ISSUE THREAD

**Issue by hairlesshobo** [Danielku15/OpenApiQuery#2]
To implement the `$select` 2 parts are missing. One is easy, the other one I was not yet able to solve easily. That's why this feature is missing so far: 

1. Queryable translation 
The actual query translation is mostly in place. The required part is happening as part of the `$expand` where a special `queryable.Select( i => new MyClass { /* all properties */ }` is generated to achieve the filtered includes. So it would be just a matter of collecting the parameters via the parser and then check on the generation of this class initializer if a member is selected or not. 

2. JSON serialization
This is the tricky part. We need to tell the JSON serializer not to write particular properties. For System.Text.Json there seems to be an approach with converters. Not sure yet if this will work out. In worst case I need to move to JSON.net and use a resolve like here: https://blog.rsuter.com/advanced-newtonsoft-json-dynamically-rename-or-ignore-properties-without-changing-the-serialized-class/

I just fear that all these systems will work on class basis. These contract resolvers/converters might work for simple selects like `/users?$select=username, firstname, lastname` but for nested properties and in combination with expands it becomes tricky: `/users?$expand=privateAddress,workAddress&$select=privateAddress/*,workAddress/zip`.

_Originally posted by @Danielku15 in https://github.com/Danielku15/OpenApiQuery/issues/1#issuecomment-555095309_

**Comment by hairlesshobo** [comment]
> 2. JSON serialization
>    This is the tricky part. We need to tell the JSON serializer not to write particular properties. For System.Text.Json there seems to be an approach with converters. Not sure yet if this will work out. In worst case I need to move to JSON.net and use a resolve like here: https://blog.rsuter.com/advanced-newtonsoft-json-dynamically-rename-or-ignore-properties-without-changing-the-serialized-class/
> 
> I just fear that all these systems will work on class basis. These contract resolvers/converters might work for simple selects like `/users?$select=username, firstname, lastname` but for nested properties and in combination with expands it becomes tricky: `/users?$expand=privateAddress,workAddress&$select=privateAddress/*,workAddress/zip`.

I'm not sure if this will help you at all or not, but the way I handled the issue of `$select` previously was completely different than this. Not saying it was the "right" or "wrong" way to do it, but maybe it'll give you some ideas. 

What I did when there was a select, I would create a new runtime object using reflection that omitted any records that were not included in the `$select` list, and then returned that. That way, the JSON serializer did not have to worry about skipping anything because the fields simply weren't there in the first place. Additionally, I performed distinct on the results as well. So in the case of a `/users` endpoint, if one of the fields was `UserType`, I could do a '/users?$select=UserType` and I would get say, two records.. one for "Administrator" and one for "Regular User". Only the `UserType` field would be shown and it would be a simple return with just two rows.

**Comment by Danielku15** [comment]
I decided to go for an own JSON serialization over an own runtime object. The main reason behind this was performance. No JSON serializer will be able to do reflection caching for dynamically generated objects which has quite a severe impact. This indirectly means that we are always traversing the whole object tree many times: First LINQ (or Entity Framework) needs to do it for the materialization of the objects, then we would generate a runtime object with the structure and finally the serializer needs to go throught the whole tree again. 

The second 2 I could merge into one using my approach. The serializer will still need some improvement and extensions to have the full feature set as the official JsonSerializers but for now it works out. 

Also as I plan to customize the serialization heavily using the Open API documents and how the models are defined there, I thought that this is the more reasonable choice.
