### ISSUE TITLE
Elegantly generate OpenAPI documentation

### ISSUE THREAD

**Issue by hairlesshobo** [Danielku15/OpenApiQuery#3]
> I would also need to find a way to dynamically document the code using OpenApiDocument. 

This is also still an open point for me. Ultimately the serializers/deserializers should honor the configuration in an OpenApiDocument (from Swashbuckle or NSwag). I also have there some needs for our project to support dynamic inclusion/exclusion of model properties, runtime renaming etc. With the EDM to CLR mapping that OData does, it works quite well.

_Originally posted by @Danielku15 in https://github.com/Danielku15/OpenApiQuery/issues/1#issuecomment-555095309_

**Comment by hairlesshobo** [comment]
I don't have any experience with Swashbuckle directly, but I am currently using NSwag. I just put together a simple OperationProcessor that can handle "replacing" the return type of the object from `OpenApiQueryResult` to `OpenApiQueryApplyResult<T>` so that when the document is generated, it displays the types that the end user would actually receive, not what is passed on to the `OpenApiQueryResultOutputFormatter` class after the controller returns. See below for what I currently have working...


![image](https://user-images.githubusercontent.com/3877800/69076018-938d2500-0a00-11ea-9267-20d804ebb75e.png)


When you say that you need to dynamically include/exclude properties, are you talking about on the return set from the OpenApiQuery enabled controller, or in the generated docs? If both, like I suspect, that could easily be handled with some attributes and a custom JsonSchemaProcessor to skip any properties that are decorated with `[InternalProperty]` or something similar.

**Comment by hairlesshobo** [comment]
I have further improved the NSwag operation processor to better display the filter parameters that can be passed to an oData action.

![image](https://user-images.githubusercontent.com/3877800/69185442-c4468a80-0ae4-11ea-846d-f5ad035d866b.png)

Gonna check in my code on my fork and create a PR for you to review.

**Comment by hairlesshobo** [comment]
#4 Submitted pull request

**Comment by Danielku15** [comment]
Closing this on in favor of #18 and #19
